### ISSUE TITLE
Happy Commits Things Todo

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/happycommits#5]
Things that need to be done:

- [x] Tag line for the site - something like, "happy commits helping our community" or something better. We should put in lorem ipsum text until we know what is going to go there.
- [x] Have the pull script never delete repos/projects
- [x] Have the pull script pull information regardless if there are first issue or help wanted issues
- [x] Have the language select be an autocomplete select box where you can filter by multiple languages
- [x] Have the pull script write all the labels to a file
- [x] Have the label select be an autocomplete select box where you can filter by multiple labels [see below](https://github.com/rubyforgood/happycommits/issues/5#issuecomment-1724172907)
- [x] Add a search bar that allows you to filter search all the projects where it searches all text (description/title/tag/etc)
- [x] Add a better search bar in the hero section -- maybe something like [this](https://tailwind-elements.com/docs/standard/forms/inputs/)
- [x] Create a issue template that walks through someone suggesting a project will all the required info
- [x] Create a PR template that has all the fields for folks submitting projects
- [x] Add footer bar
- [x] Set up github action to update the site on a regular cadence -- every 24 hours? 12? 6?
- [x] Communicate out to the sdg folks and have them tell the dpg's to add labels to their repos ie - `sdg-1`, `sdg-2`, etc. Added to [human essentials](https://github.com/rubyforgood/human-essentials) for example/testing. Also have them add `help wanted`, `good first issue`, and potentially `hacktoberfest` to issues.

##### Still need to do:

- [x] Logo and favicon for the site
- [ ] Remove infinite scroll and add in pagination
- [x] Make sure everything looks correct on mobile
- [x] Finalize the design
- [ ] Update info in the readme

##### Would be nice to do but not required for launch:

- [ ] Clean up/refactor the code into smarter components that make sense with the theme once the design is finalized
- [x] Audit dpgs and add any that we're missed from the initial API pull

**Comment by seanmarcia** [comment]
I asked for some tagline suggestions:
"Committing to a Better World."
"Code for Good, Commit for Change."
"Happy Commits, Happier Communities."
"Where Code Meets Compassion."
"Committing to Community, One Repo at a Time."
"Open Source for Open Hearts."
"Coding for Causes, Committing for Change."
"Happy Code, Happier Impact."
"Where Every Commit Counts for the Community."
"Building a Better Tomorrow, One Commit at a Time."

**Comment by seanmarcia** [comment]
Some initial mocks, not sure which, if any, will be the final design.

<img width="908" alt="image" src="https://github.com/rubyforgood/happycommits/assets/667909/abfdb0c7-149c-455e-a344-4e2a805dc111">

<img width="910" alt="image" src="https://github.com/rubyforgood/happycommits/assets/667909/6ced25c6-edd1-4cf1-8841-47ee872fcf42">

<img width="909" alt="image" src="https://github.com/rubyforgood/happycommits/assets/667909/ac16b6fc-4b90-4b01-96e3-5399c5ddc50a">

**Comment by seanmarcia** [comment]
Most of the "code" part is finished. I didn't implement the label search yet as it feels like this isn't the right way to go. With the current repos have 266 labels -- so far. That feels like too many. I think we need to do two things:
- [ ] Create an "approved list" of labels and when we are importing labels only use/save the ones on the approved list.
- [ ] Maybe just filter for labels with SDG, ie `SDG-1`, `SDG-2`, and so on.
  - [ ] If we go this route we'll probably want to map those labels to their description in the dropdown, ie - SDG-1 shows up as `SDG-1: No Poverty` in the dropdown.

**Comment by Nerajno** [comment]
Can I be a part of this?

**Comment by Cli4d** [comment]
I'm also available to help.

**Comment by seanmarcia** [comment]
@Nerajno @Cli4d Pagination is needed as well as any general code cleanup now that the design is finalized.
